import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import ContentCard from '@/components/ContentCard'
import Footer from '@/components/Footer'
import CookiesShower from '@/components/CookiesShower'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })
import Script from 'next/script'
export default function Home() {
  const [contentList, setContentList] = useState([
    {
      imageUrl: '/starbucks.png',
      title: 'Starbucks',
      content: "Experice the finest coffee and handcrafted beverages",
      url: 'https://www.starbucks.com/'
    },
    {
      imageUrl: '/peet.png',
      title: "Peet's Coffee",
      content: "Discover the rich and distinct flavors of our signature coffees",
      url: 'https://www.peets.com/'
    },
    {
      imageUrl: '/dunkin.png',
      title: "Dunkin's Donuts",
      content: "America runs on Dunkin'-grab your favorite coffee and donuts",
      url: 'https://www.dunkindonuts.com/'
    }
  ])

  return (
    <>
      <Head>
        <title>Coffe Outlets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="https://www.googletagmanager.com/gtag/js?id=G-2EMG6TDRNY"></Script>
      <Script id="google-analytics">
        {
          `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-2EMG6TDRNY');
          `
        }
      </Script>
      <div className="bg-[url('/e2AY3k8EYn.png')] bg-cover bg-center bg-no-repeat h-full flex flex-col justify-between">
        <Header></Header>
        <div className='flex flex-col justify-between items-center'>
          <div className=" flex flex-row flex-wrap items-center justify-center space-x-5">
            {
              contentList.map((item, index) => {
                return (
                  <ContentCard item={item} key={index} ></ContentCard>
                )
              })
            }
          </div>
          <div className='bg-[#E3BA8A] mt-6 w-20 h-10 text-center flex flex-col justify-center'>
            <span className='font-bold'>Feedback</span>
          </div>
        </div>
        <CookiesShower></CookiesShower>
        <Footer></Footer>
      </div >
    </>
  )
}
